"""empty message

Revision ID: fdd180206961
Revises: 7f532838e98a
Create Date: 2021-12-16 04:37:07.165652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd180206961'
down_revision = '7f532838e98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('surname', sa.String(length=15), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('course')
    # ### end Alembic commands ###
